<?php
require '../../../pdfs/fpdf.php';
require_once("../../../php/config.php");
if (!isset($_SESSION)) {
    session_start();
}
$host = DB_HOST;
$user = DB_USER;
$password = DB_PASSWORD;
$database = $_SESSION['db'];
$mysqli = new mysqli($host, $user, $password, $database);
$codigo = $_GET['id'];
//$codigo = 03215;
$query = $mysqli->query("SELECT * FROM clientes WHERE cod_cliente='$codigo'");
$datos = $query->fetch_array();
$pdf = new FPDF();
$pdf->AliasNbPages();
$pdf->AddPage('P', 'Letter');
$pdf->Image('../../../images/logo.png', 10, 10, 26, 24);
$pdf->Ln(10);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(150,6,'CERTIFICADO DE SATISFACCION DEL SERVICIO',0,0,'R');
$pdf->Cell(40, 6, 'F-6', 0, 1, 'R');
$pdf->Ln(3);
setlocale(LC_ALL,"es_ES");
if ($database == 'satpro_sm') {
    $pdf->Cell(190, 4, utf8_decode('   San Miguel, '.strftime("%A %d de %B del %Y")), 0, 1, 'C');
} elseif ($database == 'satpro') {
    $pdf->Cell(190, 4, utf8_decode('   USULUTÁN,'.strftime("%A %d de %B del %Y")), 0, 1, 'C');
} else {
    $pdf->Cell(190, 4, utf8_decode('   SUCURSAL DE PRUEBA'.strftime("%A %d de %B del %Y")), 0, 1, 'C');
}
$pdf->Ln(10);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(190,3,'SECCION ESPECIAL PARA CLIENTES',0,1,'L');
$pdf->Ln(5);
$pdf->SetFont('Arial', '', 9);
$pdf->MultiCell(190,6,utf8_decode('Al firmar esta constancia; yo: '.$datos['nombre'].', me manifiesto en conformidad con el estado del equipo que se me ha entregado, y me hago responsable de la integridad fisica del equipo. Cable sat pierde toda responsabilidad por cualquier daño ocasionado al mismo.'),0,'L',0);
$pdf->Ln(5);
$pdf->Cell(190,3,'- Previo a la instalacion se hizo de su conocimeinto el servicio a instalar y lo relacionado con el contrato:',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Tiempo de contrato',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'Megas contratados',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(190,3,'- Se le ofrecio promociones del servicio:',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Si',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'No',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(190,3,utf8_decode('- Se hizo de su conocimiento el costo monetario por daños a los equipos:'),0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Si',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'No',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(190,3,'- Le explicaron sobre el funcionamiento de los equipos:',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Si',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'No',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(190,3,'- Realizaron un test de velocidad del servicio de intenet:',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Si',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'No',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(190,3,utf8_decode('- Hicieron pruebas con la señal de TV:'),0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Si',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'No',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(190,3,utf8_decode('- Esta satisfecho con la instalacion realizada en su domicilio:'),0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Si',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'No',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(3);
$pdf->Cell(190,3,utf8_decode('- Tipo de servicio que se le a proporcionado:'),0,1,'L');
$pdf->Ln(3);
$pdf->Cell(30,3,'Digital',0,0,'R');
$pdf->Cell(50,3,'(     )',0,0,'L');
$pdf->Cell(30,3,'Analogo',0,0,'R');
$pdf->Cell(50,3,'(     )',0,1,'L');
$pdf->Ln(10);
$pdf->Cell(60,3,'F.','B',1,'L');
$pdf->Ln(1);
$pdf->Cell(60,3,$datos['nombre'],0,1,'L');
$pdf->Ln(15);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(190,3,'SECCION ESPECIAL PARA AREA TECNICA',0,1,'L');
$pdf->Ln(5);
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(50,3,'-Nivel de luz',0,0,'L');
$pdf->Cell(30,3,'','B',1,'L');
$pdf->Ln(5);
$pdf->Cell(50,3,'-Valor RX',0,0,'L');
$pdf->Cell(30,3,'','B',1,'L');
$pdf->Ln(5);
$pdf->Cell(50,3,'-MER',0,0,'L');
$pdf->Cell(30,3,'','B',0,'L');
$pdf->Cell(15,3,'BER',0,0,'R');
$pdf->Cell(30,3,'','B',0,'L');
$pdf->Cell(25,3,'POST-BER',0,0,'R');
$pdf->Cell(30,3,'','B',0,'L');
$pdf->Ln(5);
$pdf->Cell(50,3,'-Nivel de luz en caja distribuidora',0,0,'L');
$pdf->Cell(30,3,'','B',1,'L');
$pdf->Ln(10);
$pdf->Cell(60,3,'F.','B',1,'L');
$pdf->Ln(1);
$pdf->Cell(60,3,'TECNICO',0,1,'C');
$pdf->Output();
